"""add batch_jobs table

Revision ID: 13aafa45b687
Revises: 26f49b7b8456
Create Date: 2026-08-22 10:55:21.753522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13aafa45b687'
down_revision: Union[str, None] = '26f49b7b8456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'queued'")),
    sa.Column('idempotency_key', sa.UUID(), nullable=True),
    sa.Column('total_resumes', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('completed_resumes', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('batch_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_batch_jobs_job_description_id'), 'batch_jobs', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_org_id'), 'batch_jobs', ['org_id'], unique=False)
    # ### end Alembic commands ###

    # --- RLS + grants for merix_app ------------------------------------------
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON batch_jobs TO merix_app")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO merix_app"
    )
    org_ctx = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"
    op.execute("ALTER TABLE batch_jobs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE batch_jobs FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY org_isolation ON batch_jobs "
        "USING (org_id = {}) "
        "WITH CHECK (org_id = {})".format(org_ctx, org_ctx)
    )


def downgrade() -> None:
    # --- Revert RLS + grants first (table still exists) -----------------------
    op.execute("DROP POLICY IF EXISTS org_isolation ON batch_jobs")
    op.execute("ALTER TABLE batch_jobs NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE batch_jobs DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON batch_jobs FROM merix_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_jobs_org_id'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_job_description_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
