"""add retention policy and audit log

Revision ID: 2072dab8609b
Revises: f618dce73246
Create Date: 2026-08-21 20:55:22.545645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2072dab8609b'
down_revision: Union[str, None] = 'f618dce73246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_org_id'), 'audit_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_events_resume_id'), 'audit_events', ['resume_id'], unique=False)
    op.add_column('organisations', sa.Column('retention_days', sa.Integer(), server_default=sa.text('90'), nullable=False))
    # ### end Alembic commands ###

    # --- Audit log grants and RLS ----------------------------------------
    # audit_events is tenant-owned like the other data tables; the app role
    # needs CRUD and RLS must enforce org isolation.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON audit_events TO merix_app")
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public "
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO merix_app"
    )
    org_ctx = "NULLIF(current_setting('app.current_org_id', true), '')::uuid"
    op.execute("ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_events FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY org_isolation ON audit_events "
        "USING (org_id = {}) "
        "WITH CHECK (org_id = {})".format(org_ctx, org_ctx)
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Revert audit log grants and RLS first (table still exists) -------
    op.execute("DROP POLICY IF EXISTS org_isolation ON audit_events")
    op.execute("ALTER TABLE audit_events NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE audit_events DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE SELECT, INSERT, UPDATE, DELETE ON audit_events FROM merix_app")

    op.drop_column('organisations', 'retention_days')
    op.drop_index(op.f('ix_audit_events_resume_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_org_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
